# Markdownlint configuration
default: true

# Disable MD041 (first-line-heading) rule for LICENSE files
# since they are legal documents with specific formatting
MD041: false

# Allow duplicate headings in changelogs (common for Added/Changed/Fixed sections)
MD024: false

# Allow multiple H1 headings for documents with YAML frontmatter
# The title in frontmatter is often considered an H1 by the linter
MD025: false
