name: CI

"on":
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: poetry run ruff check .

      - name: Type check
        run: poetry run mypy src

      - name: Tests
        run: |
          poetry run pytest --cov=confluence_markdown \
            --cov-report=term-missing

      - name: CLI Smoke Test
        run: poetry run conmd
