name: Release

"on":
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies (no project install)
        run: poetry install --no-root

      - name: Build package (wheel + sdist)
        run: poetry build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz

      - name: Publish Release Notes to Confluence
        env:
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_SPACE: ${{ secrets.CONFLUENCE_SPACE }}
          CONFLUENCE_PARENT_PAGE: ${{ secrets.CONFLUENCE_PARENT_PAGE }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the release notes from the GitHub API
          RELEASE_NOTES=$(gh api repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} --jq '.body')

          # Publish to Confluence
          poetry run python scripts/publish_release.py "${{ github.ref_name }}" "$RELEASE_NOTES"
